In [2]:
import torch

# 定义张量的形状
tensor_shape = (10, 4)

# 创建指定形状的零张量
zero_tensor = torch.zeros(tensor_shape)

# 定义索引数组
indices = [0, 1, 2, 2, 3, 3, 3, 3, 3, 3]

# 将对应的值设置为1
for i, index in enumerate(indices):
    zero_tensor[i, index] = 1

# 输出结果张量
print(zero_tensor)


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.]])


In [11]:
import torch
data = torch.load("tensor_s.pt")

model = torch.



has_nan: tensor(False)
torch.Size([64, 25])
torch.Size([1600, 1])
tensor([2.9053, 2.2970, 2.2119, 2.0351, 2.0200, 1.6500, 1.6300, 1.4243, 1.2400,
        1.1856])


In [13]:
import torch
import torch.nn.functional as F
from torch.utils.data.sampler import BatchSampler, SubsetRandomSampler
import torch.nn as nn
from torch.distributions import Beta, Normal
from torch.distributions import Categorical



class Actor_Gaussian(nn.Module):
    def __init__(self, args):
        super(Actor_Gaussian, self).__init__()
        self.max_action = args.max_action
        self.fc1 = nn.Linear(args.state_dim, args.hidden_width)
        self.fc2 = nn.Linear(args.hidden_width, args.hidden_width)
        self.mean_layer = nn.Linear(args.hidden_width, args.continuous_action_dim)
        self.log_std = nn.Parameter(
            torch.zeros(1, args.continuous_action_dim))  # We use 'nn.Parameter' to train log_std automatically
        self.activate_func = [nn.ReLU(), nn.Tanh()][args.use_tanh]  # Trick10: use tanh
        self.discrete_action_fc = nn.Linear(args.hidden_width, args.discrete_action_dim)

        if args.use_orthogonal_init:
            print("------use_orthogonal_init------")
            orthogonal_init(self.fc1)
            orthogonal_init(self.fc2)
            orthogonal_init(self.mean_layer, gain=0.01)

    def forward(self, s):
        s = self.activate_func(self.fc1(s))
        s = self.activate_func(self.fc2(s))
        mean = (torch.tanh(self.mean_layer(s)) + 1) / 2  # [-1,1]->[-max_action,max_action]
        a_prob = torch.softmax(self.discrete_action_fc(s), dim=1)
        # mean[:, 0] *= 100
        # mean[:, 1] *= 10000

        return mean, a_prob

    def get_dist(self, s):
        mean, prob = self.forward(s)
        # print("mean_data:",mean)
        log_std = self.log_std.expand_as(mean)  # To make 'log_std' have the same dimension as 'mean'
        std = torch.exp(log_std)  # The reason we train the 'log_std' is to ensure std=exp(log_std)>0
        try:
            dist = Normal(mean, std)  # Get the Gaussian distribution
        except:
            print("s:", s, "mean:", mean, "std:", std)
            torch.save(s, "tensor_s.pt")
            torch.save(self.state_dict(), "model_error/actor.pkl")

        return dist

In [20]:
import torch
import torch.nn.functional as F
from torch.utils.data.sampler import BatchSampler, SubsetRandomSampler
import torch.nn as nn
from torch.distributions import Beta, Normal
from torch.distributions import Categorical

data = torch.load("tensor_s.pt")
print("shape:",data.shape)
actor_net =  torch.load("model_error/actor.pkl")
actor_net.eval()

self_input_data = torch.full((64,25),0.1)

print(data)

out = actor_net(self_input_data)

print(out)



shape: torch.Size([64, 25])
tensor([[ 0.3806,  0.2347,  0.0380,  ...,  0.1200,  0.2990,  0.3036],
        [ 0.2724, -0.9437, -0.3541,  ...,  0.0900,  0.2330,  0.3341],
        [ 0.0813,  0.3935, -0.0339,  ...,  0.3200,  0.2990,  0.3341],
        ...,
        [ 0.2150, -0.0887, -0.2255,  ...,  0.0100,  0.2990,  0.3341],
        [ 0.2751, -0.7553, -0.8865,  ...,  0.5000,  0.2180,  0.3341],
        [ 0.4690, -2.3496, -1.2436,  ...,  0.0100,  0.1430,  0.3341]])
(tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan